services:
  db:
    image: postgres:14-alpine
    container_name: db_mfi2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: salman
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: market
    volumes:
      - pgdata_mfi2:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U salman -d market" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 20s
  app:
    container_name: app-spring
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/market
      SPRING_DATASOURCE_USERNAME: salman
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata_mfi2: